[ai]
provider = "Anthropic"
model = "claude-3-opus-20240229"
max_tokens = 2000
anthropic_api_key = "your-api-key-here"
openai_api_key = ""

[security]
require_confirmation = true
dangerous_commands = ["rm", "sudo"]

[display]
show_execution_time = true
color_output = true

# Debug section is optional and will use defaults if not present
[debug]
show_raw_response = false
log_level = "info"
